name: DoodleGuess
options:
  bundleIdPrefix: com.matthewlam
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
settings:
  base:
    SWIFT_VERSION: 5.9
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0

targets:
  DoodleGuess:
    type: application
    platform: iOS
    sources:
      - App
      - Features
      - Models
      - Services
      - Shared
      - path: GoogleService-Info.plist
        type: file
        buildPhase: resources
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: DoodleGuess
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - doodleguess
        UIBackgroundModes:
          - remote-notification
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.doodleguess
        PRODUCT_NAME: DoodleGuess
        CODE_SIGN_ENTITLEMENTS: App/DoodleGuess.entitlements
    dependencies:
      - target: DoodleWidget
        embed: true
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseFunctions
      - package: Firebase
        product: FirebaseStorage

  DoodleWidget:
    type: app-extension
    platform: iOS
    sources:
      - DoodleWidget
      - Shared
    info:
      path: DoodleWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
          NSExtensionAttributes:
            NSExtensionWidgetKind: DoodleWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.doodleguess.widget
        PRODUCT_NAME: DoodleWidget
        CODE_SIGN_ENTITLEMENTS: DoodleWidget/DoodleWidget.entitlements

  DoodleGuessTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DoodleGuessTests
    info:
      path: DoodleGuessTests/Info.plist
      properties: {}
    dependencies:
      - target: DoodleGuess
